core/urls.py
from django.conf.urls import url, include
import core.views as views


urlpatterns = [
    url(r'^$', views.home_page, name='home-page'),

    url(r'^(?P<slug>contribute)/?$', views.contribute, name='contribute'),
    url(r'^contribute/(?P<slug>guidelines)/$', views.static_page, name='static_page'),

    url(r'^(?P<slug>about)/$', views.static_page, name='static_page'),
    url(r'^about/(?P<slug>pari\-teachers\-students)/$', views.static_page, name='static_page'),
    url(r'^about/(?P<slug>about\-the\-editor)/$', views.static_page, name='static_page'),
    url(r'^about/(?P<slug>acknowledgements)/$', views.static_page, name='static_page'),

    url(r'^legal/(?P<slug>terms\-and\-conditions)/$', views.static_page, name='static_page'),
    url(r'^legal/(?P<slug>copyright)/$', views.static_page, name='static_page'),

    url(r'^contact-us/$', views.contact_us, name='contact_us'),
    url(r'^(?P<slug>donate)/$', views.static_page, name='static_page'),

    url(r'^pages/guidelines/$', views.guidelines, name='guidelines'),
    url(r'^pages/pari-teachers-students/$', views.pari_teachers_students, name='pari_teachers_students'),
    url(r'^pages/contribute-to-faces/$', views.contribute_to_faces, name='contribute_to_faces'),
    url(r'^pages/donate/$', views.donate, name='donate'),
    url(r'^pages/about/$', views.about, name='about'),
    url(r'^pages/acknowledgements/$', views.acknowledgements, name='acknowledgements'),
    url(r'^pages/about-the-editor/$', views.founders, name='founders'),
    url(r'^pages/(?P<slug>.+)/$', views.static_page, name='static_page'),
    url(r'^sitemap\.xml$', views.sitemap_index, name='sitemap_index'),
    url(r'^sitemap-(?P<year>\d+)\.xml', views.sitemap_year, name='sitemap_year'),
]

core/models.py
from __future__ import unicode_literals

from django import forms
from django.conf import settings
from django.urls import reverse
import django.db.models.deletion
from django.db import models
from django.db.models import Q
from six import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from wagtail.admin.edit_handlers import MultiFieldPanel, \
    StreamFieldPanel, PageChooserPanel, FieldPanel
from wagtail.admin.forms import WagtailAdminPageForm
from wagtail.core import blocks
from wagtail.core.blocks import StructBlock, IntegerBlock
from wagtail.core.fields import RichTextField
from wagtail.core.fields import StreamField
from wagtail.core.models import Page
from wagtail.images.blocks import ImageChooserBlock
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.images.formats import get_image_format
from wagtail.images.models import AbstractImage, AbstractRendition
from wagtail.search import index

from album.models import Album
from article.models import Article
from category.models import Category
from core.utils import get_translations_for_page, SearchBoost, get_unique_photographers,construct_guidelines


@python_2_unicode_compatible
class StaticPage(Page):
    # TODO: Keep it simple for now.
    content = RichTextField(blank=True)
    language = models.CharField(max_length=7, choices=settings.LANGUAGES)

    def __str__(self):
        return self.title

    content_panels = Page.content_panels + [
        FieldPanel('content'),
        FieldPanel('language'),
    ]

    search_fields = Page.search_fields + [
        index.SearchField('title', partial_match=True, boost=SearchBoost.TITLE),
        index.SearchField('language'),
        index.FilterField('get_search_type'),
        index.FilterField('language'),
        index.SearchField('content')
    ]

    def get_search_type(self):
        return self.__class__.__name__.lower()

    def get_absolute_url(self):
        return reverse("static_page", kwargs={"slug": self.slug})


class FeaturedSectionBlock(StructBlock):
    title = blocks.CharBlock(required=False)
    link_text = blocks.CharBlock(required=False)
    url = blocks.CharBlock()
    position_from_left = IntegerBlock(default=9, required=True, min_value=0, max_value=75,
                                      help_text="Value in percentage (Max: 75)")
    position_from_top = IntegerBlock(default=30, required=True, min_value=0, max_value=40,
                                     help_text="Value in percentage (Max: 40)")
    featured_image = ImageChooserBlock()
    featured_image_label = blocks.CharBlock(required=False)


class HomePageAdminMediaForm(WagtailAdminPageForm):
    def __init__(self, *args, **kwargs):
        super(HomePageAdminMediaForm, self).__init__(*args, **kwargs)
        self.fields['talking_album'] = forms.CharField(max_length=50,
                                                       widget=forms.Select(
                                                           choices=Album.objects.live().filter(
                                                               ~Q(slides__audio='')).distinct().values_list(
                                                               'page_ptr_id', 'title')))
        self.fields['photo_album'] = forms.CharField(max_length=50,
                                                     widget=forms.Select(choices=Album.objects.live().filter(
                                                         Q(slides__audio='')).distinct().values_list('page_ptr_id',
                                                                                                     'title')))
        self.fields['video'] = forms.CharField(max_length=50,
                                               widget=forms.Select(choices=Article.objects.live().filter(
                                                   Q(categories__name='VideoZone')).values_list('page_ptr_id',
                                                                                                'title')))

    def clean_talking_album(self):
        talking_album = Album.objects.get(page_ptr_id=self.cleaned_data['talking_album'])
        return talking_album

    def clean_photo_album(self):
        photo_album = Album.objects.get(page_ptr_id=self.cleaned_data['photo_album'])
        return photo_album

    def clean_video(self):
        video = Article.objects.get(page_ptr_id=self.cleaned_data['video'])
        return video


class HomePageAdminForm(HomePageAdminMediaForm):
    in_focus_title = forms.CharField(required=True)
    in_focus_link = forms.CharField(required=True)
    in_focus_link_text = forms.CharField(required=True)

    def clean_in_focus_page1(self):
        page1 = self.cleaned_data['in_focus_page1']
        if not page1:
            raise forms.ValidationError(_('Please add a page'))
        return page1

    def clean_in_focus_page2(self):
        page2 = self.cleaned_data['in_focus_page2']
        if not page2:
            raise forms.ValidationError(_('Please add a page'))
        return page2


@python_2_unicode_compatible
class HomePage(Page):
    featured_content = StreamField([
        ("featured_section", FeaturedSectionBlock()),
    ], blank=True, null=True)

    carousel_title = models.TextField(blank=False, null=False, default='Latest On PARI')
    # TODO: Carousel is temporary and being phased out
    carousel_0 = models.ForeignKey("wagtailcore.Page",
                                   null=True, blank=True,
                                   on_delete=models.SET_NULL,
                                   related_name="+")
    carousel_1 = models.ForeignKey("wagtailcore.Page",
                                   null=True, blank=True,
                                   on_delete=models.SET_NULL,
                                   related_name="+")
    carousel_2 = models.ForeignKey("wagtailcore.Page",
                                   null=True, blank=True,
                                   on_delete=models.SET_NULL,
                                   related_name="+")
    carousel_3 = models.ForeignKey("wagtailcore.Page",
                                   null=True, blank=True,
                                   on_delete=models.SET_NULL,
                                   related_name="+")
    carousel_4 = models.ForeignKey("wagtailcore.Page",
                                   null=True, blank=True,
                                   on_delete=models.SET_NULL,
                                   related_name="+")
    carousel_5 = models.ForeignKey("wagtailcore.Page",
                                   null=True, blank=True,
                                   on_delete=models.SET_NULL,
                                   related_name="+")
    carousel_6 = models.ForeignKey("wagtailcore.Page",
                                   null=True, blank=True,
                                   on_delete=models.SET_NULL,
                                   related_name="+")
    carousel_7 = models.ForeignKey("wagtailcore.Page",
                                   null=True, blank=True,
                                   on_delete=models.SET_NULL,
                                   related_name="+")
    carousel_8 = models.ForeignKey("wagtailcore.Page",
                                   null=True, blank=True,
                                   on_delete=models.SET_NULL,
                                   related_name="+")
    carousel_9 = models.ForeignKey("wagtailcore.Page",
                                   null=True, blank=True,
                                   on_delete=models.SET_NULL,
                                   related_name="+")
    in_focus_title = models.TextField(blank=True, null=True, verbose_name="Title")
    in_focus_link = models.TextField(blank=True, null=True, verbose_name="Link")
    in_focus_link_text = models.TextField(blank=True, null=True, verbose_name="Link Text")
    in_focus_page1 = models.ForeignKey("wagtailcore.Page",
                                       null=True, blank=True,
                                       on_delete=models.PROTECT,
                                       related_name="+", verbose_name="Page one")
    in_focus_page2 = models.ForeignKey("wagtailcore.Page",
                                       null=True, blank=True,
                                       on_delete=models.PROTECT,
                                       related_name="+", verbose_name="Page two")

    talking_album = models.ForeignKey("album.Album",
                                      null=True, blank=True, related_name='+', on_delete=models.PROTECT)
    photo_album = models.ForeignKey("album.Album",
                                    null=True, blank=True, related_name='+', on_delete=models.PROTECT)
    video = models.ForeignKey("article.Article",
                              null=True, blank=True, on_delete=models.PROTECT)

    language = models.CharField(max_length=7, choices=settings.LANGUAGES)

    content_panels = Page.content_panels + [
        MultiFieldPanel([StreamFieldPanel('featured_content')], heading="Featured Content", classname="collapsible "),
        MultiFieldPanel([
            FieldPanel('carousel_title'),
            PageChooserPanel('carousel_0'),
            PageChooserPanel('carousel_1'),
            PageChooserPanel('carousel_2'),
            PageChooserPanel('carousel_3'),
            PageChooserPanel('carousel_4'),
            PageChooserPanel('carousel_5'),
            PageChooserPanel('carousel_6'),
            PageChooserPanel('carousel_7'),
            PageChooserPanel('carousel_8'),
            PageChooserPanel('carousel_9'),
        ], "Carousel"),
        MultiFieldPanel([
            FieldPanel('in_focus_title'),
            FieldPanel('in_focus_link'),
            FieldPanel('in_focus_link_text'),
            PageChooserPanel('in_focus_page1'),
            PageChooserPanel('in_focus_page2'),
        ], "In Focus"),
        FieldPanel('talking_album'),

core/forms.py
from django import forms

from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        exclude = ("created_on",)
        model = Contact

core/templates/core/add_object.html
{% load i18n %}
<div class="tab-content">
  <header class="active nice-padding">
    <div class="row">
      <h1>{% blocktrans %}Add {{ name }} {% endblocktrans %}</h1>
    </div>
  </header>
  <div class="tab-content">
    <section class="nice-padding active">
      <form action="{{ add_object_url }}" method="POST" class="add-object">{% csrf_token %}
	      <ul class="fields">
	        {% for field in form %}
	        {% if field.is_hidden %}
	        {{ field }}
	        {% else %}
	        {% include "wagtailadmin/shared/field_as_li.html" with field=field %}
	        {% endif %}
	        {% endfor %}
	        <li><input type="submit" value="{% blocktrans %}Add {{ name }} {% endblocktrans %}" /></li>
	      </ul>
      </form>
    </section>
  </div>
</div>

core/templates/core/contact_us.html
{% extends "base.html" %}
{% load i18n wagtailcore_tags %}

{% block meta_title %}
{% trans "Contact PARI" %}
{% endblock %}

{% block meta_description %}{% trans "PARI Contact Us" %}{% endblock %}

{% block extra_css %}
    <link type="text/less" rel="stylesheet" href="{{ STATIC_URL }}css/v2/pages/contact-us.less">
    <link type="text/less" rel="stylesheet" href="{{ STATIC_URL }}css/v2/pages/static_page.less">
{% endblock %}

{% block main %}
<div class="container" id="contact-pari">
    {% url "contribute" as contribute_url %}
    {% url "static_page" slug="guidelines" as guidelines_url %}
    {% url "static_page" slug="donate" as donate_url %}

    <h1>{% trans "Contact PARI" %}</h1>
    <h4 class="font-xl">{% trans "TO CONTRIBUTE CONTENT" %}</h4>
    <p class="section-content">
        {% blocktrans trimmed %}
        Please visit the <a href="https://script.google.com/macros/s/AKfycbyHC82VzoPpoUqjrcNj8Yg0kBo904g-om2cdjH0d_BRt0L1b5aA/exec" target="_blank">
        content upload form</a> and the <a href="{{ guidelines_url }}">guidelines</a> for details.
        {% endblocktrans %}
    </p>

    <h4 class="font-xl">{% trans "TO DONATE TO PARI" %}</h4>
    <p class="section-content">{% blocktrans trimmed %}Do see our <a href="{{ donate_url }}">donate</a> page for details.{% endblocktrans %}</p>

    <h4 class="font-xl">{% trans "WANT TO VOLUNTEER FOR PARI?" %}</h4>
    <p class="section-content">{% trans "Help us understand your skills and interests by filling up this" %} <a href="https://docs.google.com/forms/d/e/1FAIpQLScfpZfiT28pInGrwKxiIkVrztNMzATkOHmgEXfJwcgkT8nLkg/viewform" target="_blank">form</a>.</p>

    <form method="post" action="{% url "contact_us" %}">{% csrf_token %}
        <h4 class="font-xl">{% trans "OTHER QUESTIONS?" %}</h4>
        <p>{% trans "Write to us using this form:" %}</p>
        <div class="form">
            <div class="form-group">
                <label>{{ contact_form.name.label | upper }}</label>
                {{ contact_form.name }}
            </div>
            <div class="form-group">
                <label>{{ contact_form.email.label | upper }}</label>
                {{ contact_form.email }}
            </div>
            <div class="form-group">
                <label>{{ contact_form.message.label | upper }}</label>
                {{ contact_form.message }}
            </div>
            <div class="form-group">
                <input type="submit" class="primary" value="{% trans "Send" %}">
            </div>
            </div>
  </form>
</div>
{% endblock %}

core/templates/core/contribute-to-faces.html
{% extends "base.html" %}
{% load i18n wagtailcore_tags %}

{% block meta_title %}{% trans "Let’s FACE it" %}{% endblock %}
{% block meta_description %}{% trans "Contribute to the growing FACES repository and help PARI capture the sheer diversity of the people of India." %}{% endblock %}

{% block extra_css %}
   <link type="text/less" rel="stylesheet" href="{{ STATIC_URL }}css/v2/pages/contribute_faces.less">
{% endblock %}

{% block opengraph_block %}
    {% include "core/includes/media_sharing_meta.html" with title="Let’s FACE it" description="Contribute to FACES. Help PARI capture the sheer diversity of the people of our country." url=request.get_full_path image_url=STATIC_URL|add:"img/faces-contr-banner.png" %}
{% endblock %}

{% block main %}
    <div class="container" >
        <div class="contribute-title">
            <div class="col-lg-9 col-md-9 col-sm-12 make-left">
                <h1>{% trans "Let’s FACE it" %}</h1>
                <p class="title-strap" >{% blocktrans trimmed %}Contribute to FACES. Help PARI capture the sheer diversity of the people of our country. Join us in our endeavour to create a facial map of the most diverse societies on earth – those across rural India.{% endblocktrans %}</p>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-12 make-left">
                <a href="{{ link }}" target="_blank"><div class="upload-button top-button" >
                    <i class="fa fa-upload"></i>
                    <span>{% trans "Upload a FACE photo" %}</span>
                </div></a>
            </div>
        </div>
    </div>
    <div class="full-row image-holder">
        <img src="{{ STATIC_URL }}img/faces-contr-banner.png" alt="" />
    </div>
    <div class="container" >
        <div class="col-lg-8 col-md-8 col-sm-12 contribute-description make-left">
            <h4>{% blocktrans trimmed %}<a href="/categories/faces/k/tami/"> <span><u>Tami</u></span></a> in Kalahandi, Odisha, has a very Indian face. So does <a href="/categories/faces/k/kottavarayan-rajendran/"><span><u>Rajendran</u></span> </a> of Kanchipuram in Tamil Nadu. So too, <a href="/categories/faces/s/ohame/"><span><u>Ohame</u></span></a> of the Andamans and Michi Yaring of Arunachal Pradesh. And not one of them resembles the other in the slightest.{% endblocktrans %}</h4>
            <p>{% blocktrans trimmed %}PARI aims to record Indian faces from every single block and district in the country. That’s right — thousands and thousands of FACES, capturing the astonishing diversity of how Indians look. From every single district (and each block of every district) we aim to put up portraits of at least one adult male, one adult female and one child or adolescent. This is a gigantic exercise that will take years to complete and demands the widest participation. Anyone can take part in it provided the photograph is good enough.{% endblocktrans %}</p>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12 how-to-contri make-left ">
            <hr>
            <h5 class="primary-contr-heading">{% trans "HOW YOU CAN CONTRIBUTE" %}</h5>
            <h5 class="sub-contr-heading">{% trans "Upload photos" %}</h5>
            <p class="sub-contr-desc">{% trans "It is very important that the photograph you send to PARI is accompanied by the details of the person in the picture." %}</p>
             {% url "static_page" slug="guidelines" as guidelines %}
            <p class="primary-contr-link">{% blocktrans trimmed %}For more on these details, please read the <a itemprop="url" href="{{ guidelines }}#section-1-7"><u>guidelines</u></a> for FACES.{% endblocktrans %}</p>
            <a href="{{ link }}" target="_blank">
                <div class="upload-button bottom-button">
                    <i class="fa fa-upload"></i>
                    <span>{% trans "Upload a FACE photo" %}</span>
                </div>
            </a>
        </div>
    </div>
{% endblock %}

core/templates/core/contribute.html
{% extends "base.html" %}
{% load i18n %}

{% block meta_title %}
    {% blocktrans with site_name=site.site_name %} Contribute to {{ site_name }} {% endblocktrans %}
{% endblock %}
{% block meta_description %}{% trans "Join us in building a unique national knowledge repository on rural India. We need writers, editors, photographers, filmmakers, translators, researchers, and more." %}{% endblock %}

{% block opengraph_block %}
    {% include "core/includes/media_sharing_meta.html" with title="India’s biggest archive of itself needs everyone to participate" description="Join us in building a unique national knowledge repository on rural India. You can start by telling us something about yourself." url=request.get_full_path type="url" image_url=STATIC_URL|add:"img/share_faces_collage.jpg"%}
{% endblock %}

{% block extra_css %}
    <link type="text/less" rel="stylesheet" href="{{ STATIC_URL }}css/v2/forms/form-elements.less">
    <link type="text/less" rel="stylesheet" href="{{ STATIC_URL }}css/v2/pages/contribute.less">
    <link type="text/less" rel="stylesheet" href="{{ STATIC_URL }}css/v2/pages/static_page.less">
{% endblock %}

{% block main %}
    <div id="contribute">
        <div class="content container">
            <h1>{% trans "India’s biggest archive of itself needs everyone to participate" %}</h1>
            <p class="contribute-heading">{% trans "COVER YOUR COUNTRY – HERE’S HOW" %}</p>
            <p>{% trans "Join us in building a unique national knowledge repository on rural India." %}</p>
            <p>{% trans "You can start by telling us something about yourself." %}</p>
            <a href="https://docs.google.com/forms/d/e/1FAIpQLScfpZfiT28pInGrwKxiIkVrztNMzATkOHmgEXfJwcgkT8nLkg/viewform"
               target="_blank" class="btn primary">{% trans "Fill the profile form" %}</a>
            <hr/>

            <div>
                <p class="contribute-heading">{% trans "CONTRIBUTE CONTENT" %}</p>
                <div class="contribute-cols row">
                    <div class="col-sm-12 col-md-4 col-lg-4">
                        <div>
                            <i class="fa fa-pencil-alt"></i>
                            <p class="contribute-col-heading"> {% trans "Write / Edit / Photograph" %} </p>
                        </div>
                        <p>
                            {% blocktrans trimmed %}You could write content for existing films or edit content that has been written but needs
                            the
                            careful eye of an editor. You can also write independent content for our print section. You
                            could translate the subtitles of films on PARI into other languages. Having those in as many
                            Indian languages as possible is a major objective. You can also translate other written
                            content
                            into different languages.{% endblocktrans %}
                        </p>
                        <hr/>
                        <div class="help-text">
                            {% blocktrans trimmed %}Help us understand your skills and interests by filling in this <a
                                href="https://docs.google.com/forms/d/e/1FAIpQLScfpZfiT28pInGrwKxiIkVrztNMzATkOHmgEXfJwcgkT8nLkg/viewform"
                                target="_blank">Profile Form</a>.{% endblocktrans %}
                        </div>
                        <hr/>
                        <div class="help-text">
                            {% blocktrans trimmed %}Upload your articles, photos, document with content ideas through the <a
                                href="https://script.google.com/macros/s/AKfycbyHC82VzoPpoUqjrcNj8Yg0kBo904g-om2cdjH0d_BRt0L1b5aA/exec"
                                target="_blank">Content Upload Form</a>.{% endblocktrans %} 
                        </div>
                        <hr/>
                        <div class="help-text">
                            {% blocktrans trimmed %}To contribute to the Faces category, upload the photos and details through the <a
                                href="https://script.google.com/macros/s/AKfycbzMQwyY8P1t7CT0_ylmPfSDz7WiSTVHWtL-Yf0UhtoYOIWQfMf5/exec"
                                target="_blank">Faces Form</a>.{% endblocktrans %}
                        </div>
                        <hr/>
                    </div>
                    <div class="col-sm-12 col-md-4 col-lg-4">
                        <div>
                            <i class="fa fa-film"></i>
                            <p class="contribute-col-heading"> {% trans "Make a film" %} </p>
                        </div>
                        <p>
                            {% blocktrans trimmed %}You can produce content for the archive by making films like the ones you already see on
                            this
                            website, so long as these are within PARI’s mandate and objectives. Get in touch with us to
                            know
                            what would be suitable for the archive. The basic principle: it’s got to be on the everyday
                            lives of everyday people in rural India. Share your ideas about what topics/ areas you wish
                            to
                            make a film on. We can take it further from there. Know that you can record content for PARI
                            on
                            your cell phone camera. Please share your audio/video clip links through this <a
                                href="https://script.google.com/macros/s/AKfycbyHC82VzoPpoUqjrcNj8Yg0kBo904g-om2cdjH0d_BRt0L1b5aA/exec"
                                target="_blank">Content Upload Form</a>.{% endblocktrans %}
                        </p>
                    </div>
                    <div class="col-sm-12 col-md-4 col-lg-4">
                        <div>
                            <i class="fa fa-binoculars"></i>
                            <p class="contribute-col-heading"> {% trans "Research" %} </p>
                        </div>
                        {% url "resource-list" as resource_list %}
                        <p>{% blocktrans trimmed %}Find online content already on the archive and send us links to it. Or research a vital topic
                            –
                            for instance, the lives of agricultural labourers in rural India – and collaborate with us
                            on
                            building a fund of information, photographs and data on that subject. Besides, you can send
                            us
                            any studies or reports in electronic form which you know of and that are relevant to rural
                            India. Have a look at PARI's <a href={{ resource_list }}>'Resources'</a> section to know what’s already there and get a
                            better
                            idea of what we’re looking for. Do share any relevant reports you find through this <a
                                    href="https://script.google.com/macros/s/AKfycbyHC82VzoPpoUqjrcNj8Yg0kBo904g-om2cdjH0d_BRt0L1b5aA/exec"
                                    target="_blank">Content Upload Form</a>.{% endblocktrans %} </p>
                    </div>
                </div>
                <div class="contribute-cols row">
                    <div class="col-sm-12 col-md-4 col-lg-4">
                        <div>
                            <i class="fa fa-language"></i>
                            <p class="contribute-col-heading"> {% trans "Translate" %} </p>
                        </div>
                        <p>{% blocktrans trimmed %}Help us by translating content into Indian languages. Please help us understand your skills
                            and
                            interests by filling in this <a
                                    href="https://docs.google.com/forms/d/e/1FAIpQLScfpZfiT28pInGrwKxiIkVrztNMzATkOHmgEXfJwcgkT8nLkg/viewform"
                                    target="_blank">Profile Form</a>.{% endblocktrans %}</p>
                    </div>
                    <div class="col-sm-12 col-md-4 col-lg-4">
                        <div>
                            <i class="fa fa-user-circle"></i>
                            <p class="contribute-col-heading"> {% trans "FACES" %} </p>
                        </div>
                        <p>{% blocktrans trimmed %}Do you have FACES to contribute to the only and largest database recording India’s facial
                            diversity?{% endblocktrans %}</p>
                        <a href="{% url "contribute_to_faces" %}" class="btn primary">{% trans "Contribute to Faces" %}</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="ready-to-upload">
            <div class="container">
                <p class="contribute-heading">{% trans "READY TO UPLOAD?" %}</p>
                {% url "static_page" slug="guidelines" as guidelines %}
                <p>{% blocktrans trimmed %}Is your content ready to upload? Do go through the <a
                        href={{ guidelines }}>PARI content guidelines</a> to ensure you know what’s
                    required.{% endblocktrans %}</p>
                <a href="https://script.google.com/macros/s/AKfycbyHC82VzoPpoUqjrcNj8Yg0kBo904g-om2cdjH0d_BRt0L1b5aA/exec"
                   target="_blank" class="btn primary">{% trans "Upload content" %}</a>
            </div>
        </div>

        <div class="support-a-pari-project container">
            <p class="contribute-heading">{% trans "DONATE – SUPPORT A PARI PROJECT" %}</p>
            <p>{% blocktrans trimmed %}You can back ongoing PARI projects by funding them. Or pitch one yourself on an aspect of rural India
                from your home state or district that you believe demands attention.{% endblocktrans %}</p>
            <a href="{% url "static_page" slug="donate" %}" class="btn primary">{% trans "Donate to PARI" %}</a>
        </div>
    </div>
{% endblock %}

core/templates/core/static_page.html
{% extends "base.html" %}
{% load i18n %}
{% load wagtailcore_tags %}

{% block meta_title %}
{{ self.title }}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block main %}
<div class="pull-right">
{% if translations and translations|length > 1 and show_language_filter %}
    <span class="dropdown translations">
	<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
	    {% trans "Choose language" %}
	    <span class="caret"></span>
	</button>
	<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
	    {% for translation in translations %}
	    <li role="presentation"><a role="menuitem" tabindex="{{ forloop.counter0 }}" href="{{ translation.get_absolute_url }}">{{ translation.get_language_display }}</a></li>
	    {% endfor %}
	</ul>
    </span>
{% endif %}
</div>
<div class="container">
    <div class="special-bullets">
        {{ self.content|richtext }}
    </div>
</div>
{% endblock %}

core/templates/core/story_of_pari.html
{% extends "base.html" %}
{% load i18n %}
{% load wagtailcore_tags %}
{% block meta_title %} The story of PARI {% endblock %}
{% block meta_description %} Rural India — a living journal, a breathing archive  {% endblock %}

{% block extra_css %}
   <link type="text/less" rel="stylesheet" href="{{ STATIC_URL }}css/v2/pages/story_of_pari.less">
{% endblock %}

{% block main %}
    <div class="container story-of-pari"></div>
{%  endblock %}